### ISSUE TITLE
[3pts] Create Lambda Function.

### ISSUE THREAD

**Issue by celineMaina** [celineMaina/AWS-Cloud-Resume#7]
## Task
- [ ] Create a Lambda function.
- [ ] Create a role for the Lambda function.
- [ ] Create a function URL.
- [ ] Test Lambda function.

### Description
- Write the Lambda function in Python to retrieve the JSON data from DynamoDB
- Implement error handling.
- Create an IAM role with the required permissions to access DynamoDB
- Assign the role to your Lambda function.
- Set up a function URL to invoke the Lambda function via HTTP requests.
- Ensure the URL is secure and only accessible to authorized users or applications.
