### ISSUE TITLE
[6pts] Set up a CI/CD Pipeline

### ISSUE THREAD

**Issue by celineMaina** [celineMaina/AWS-Cloud-Resume#8]
## Task
- [ ] Write GitHub Actions Workflow.
- [ ] Set Up Repository Secrets.
- [ ] Test GitHub Actions.

### Description
- Write a workflow in YAML that defines the CI/CD pipeline.
- Add repository secrets on GitHub settings.
- Add GitHub extension on VS Code.
- Ensure that the workflow works correctly by pushing changes to the repository.
- Verify that the actions work seamlessly, troubleshoot any issues.
